name: Test & Deploy
on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14
    - run: shellcheck deploy.sh
    - run: npm install
    - run: npm run lint
    - run: npm test
      env:
        FORCE_COLOR: 3
  deploy:
    name: Deploy
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    needs: test
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - run: echo $GITHUB_SHA > version.txt
    - run: bash ./deploy.sh
      env:
        SERVER: ${{ secrets.NOEMBED_SERVER }}
        SERVER_PUBLIC_KEY: ${{ secrets.NOEMBED_PUBLIC_KEY }}
        SERVER_DEPLOY_KEY: ${{ secrets.NOEMBED_DEPLOY_KEY }}
  verify-deploy:
    name: Verify Deploy
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    needs: deploy
    runs-on: ubuntu-20.04
    steps:
    - run: |
        for i in {1..10}; do
          DEPLOYED_VERSION="$(curl -s https://participate.whatwg.org/version)"
          if [[ "$DEPLOYED_VERSION" = "$GITHUB_SHA" ]]; then
            echo "$GITHUB_SHA deploy verified!"
            exit 0
          fi
          echo "$GITHUB_SHA not yet deployed, current version is $DEPLOYED_VERSION. Waiting before checking again..."
          sleep 60
        done
        echo "$GITHUB_SHA not deployed after 10 minutes."
        exit 1
      shell: bash
