name: Test & Deploy
on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
  # Trigger for changes in the whatwg/sg repo.
  repository_dispatch:
    types:
    - sg_repo_updated
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 24
    - run: npm install
    - run: npm run lint
    - run: npm test
      env:
        FORCE_COLOR: 3
  # The deploy happens on DigitalOcean, this just checks that it eventually
  # succeeds.
  verify-deploy:
    name: Verify Deploy
    if: ${{ (github.event_name == 'push' || github.event_name == 'repository_dispatch') && github.ref == 'refs/heads/main' }}
    needs: test
    runs-on: ubuntu-latest
    steps:
    - run: |
        for i in {1..10}; do
          DEPLOYED_VERSION="$(curl -s https://participate.whatwg.org/version)"
          if [[ "$DEPLOYED_VERSION" = "$GITHUB_SHA" ]]; then
            echo "$GITHUB_SHA deploy verified!"
            exit 0
          fi
          echo "$GITHUB_SHA not yet deployed, current version is $DEPLOYED_VERSION. Waiting before checking again..."
          sleep 60
        done
        echo "$GITHUB_SHA not deployed after 10 minutes."
        exit 1
      shell: bash
